### ISSUE TITLE
bug: does not properly validate assertion of status code

### ISSUE THREAD

**Issue by ethanholz** [abhimanyu003/probe#1]
Hello! When using `probe` to validate status codes, it will pass regardless of what the status code is set to. An example of this is running the following test case: 
```yaml
name: Writing Test
stages:
  - name: first stage
    request:
      url: "https://google.com"
      method: GET
    assert:
      status: 200

```

This test case should fail with a status code of 301 but instead you will receive a pass.
