### ISSUE TITLE
how to use negate assertion (not equal / is not empty)

### ISSUE THREAD

**Issue by muhfaris** [abhimanyu003/probe#2]
Hi, i try to write test auth with assertion the token is not empty ( not equal = ''). 
I can't use the `want` key, do you know how to accomplish it?

this sample from documentation
```
name: auth and get user
stages:
  - name: auth
    request:
      url: "https://dummyjson.com/auth/login"
      method: POST
      formData:
        username: kminchelle
        password: 0lelplR
    assert:
      status: 200
    export:
      body:
        - select: .id
          as: userId # setting id as userId variable
        - select: .token
          as: token # setting token id as variable
```
